# Generated by Django 4.2 on 2023-06-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageEmp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.AddField(
            model_name='employee',
            name='pnumber',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
