# Generated by Django 4.2 on 2023-06-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageEmp', '0002_delete_asset_delete_leave_employee_pnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assetName', models.CharField(max_length=100)),
                ('sno', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
    ]
