# Generated by Django 4.2 on 2023-06-12 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageEmp', '0003_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='password',
            new_name='tpass',
        ),
    ]
