# Generated by Django 4.2 on 2023-06-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageEmp', '0004_rename_password_employee_tpass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='employee_id',
        ),
    ]
