# Generated by Django 4.2 on 2023-06-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageEmp', '0005_rename_id_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.AutoField(db_column='employee_id', primary_key=True, serialize=False),
        ),
    ]
