# Generated by Django 4.2 on 2023-06-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageEmp', '0006_alter_employee_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_id',
            new_name='id',
        ),
    ]
