# Generated by Django 4.2 on 2023-06-20 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageEmp', '0007_rename_employee_id_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manageEmp.employee'),
        ),
    ]
