# Generated by Django 4.2 on 2023-06-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageEmp', '0008_asset_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='employee',
        ),
    ]
