# Generated by Django 4.2.4 on 2023-09-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageEmp', '0009_remove_asset_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='assetName',
            new_name='asset_name',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='sno',
            new_name='serial_number',
        ),
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
