# Generated by Django 4.2.4 on 2023-09-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageEmp', '0010_rename_assetname_asset_asset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.AutoField(db_column='asset_id', primary_key=True, serialize=False),
        ),
    ]
